const cafesData = [
    // ANDHRA PRADESH

    {
        id: 1,
        name: "Bean Board",
        city: "Visakhapatnam",
        address: "Siripuram, Visakhapatnam",
        lat: 17.7246,
        lng: 83.3065,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "study"],
        openHours: { open: 9, close: 22 },
        rating: 4.5,
        phone: "+91 891 256 7000"
    },
    {
        id: 2,
        name: "Cafe Coffee Day",
        city: "Visakhapatnam",
        address: "MVP Colony, Visakhapatnam",
        lat: 17.7381,
        lng: 83.3193,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["quick", "reading"],
        openHours: { open: 8, close: 23 },
        rating: 4.1,
        phone: "+91 891 270 1111"
    },
    {
        id: 3,
        name: "Pincode 17",
        city: "Visakhapatnam",
        address: "Lawsons Bay Colony, Visakhapatnam",
        lat: 17.7289,
        lng: 83.3158,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout", "meeting"],
        openHours: { open: 11, close: 23 },
        rating: 4.3,
        phone: "+91 891 258 4444"
    },

    {
        id: 4,
        name: "Cafe Coffee Day",
        city: "Vijayawada",
        address: "Benz Circle, Vijayawada",
        lat: 16.4999,
        lng: 80.6560,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "work"],
        openHours: { open: 8, close: 23 },
        rating: 4.2,
        phone: "+91 866 258 7711"
    },
    {
        id: 5,
        name: "Barista",
        city: "Vijayawada",
        address: "Governorpet, Vijayawada",
        lat: 16.5141,
        lng: 80.6352,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meeting"],
        openHours: { open: 9, close: 22 },
        rating: 4.3,
        phone: "+91 866 241 5566"
    },
    {
        id: 6,
        name: "Tea Post",
        city: "Vijayawada",
        address: "Moghalrajpuram, Vijayawada",
        lat: 16.5060,
        lng: 80.6485,
        wifi: false,
        sockets: "low",
        seating: "basic",
        ac: false,
        bestFor: ["quick", "hangout"],
        openHours: { open: 7, close: 22 },
        rating: 4.2,
        phone: "+91 90000 12345"
    },

    {
        id: 7,
        name: "Cafe Coffee Day",
        city: "Tirupati",
        address: "KT Road, Tirupati",
        lat: 13.6340,
        lng: 79.4206,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["quick", "reading"],
        openHours: { open: 8, close: 22 },
        rating: 4.0,
        phone: "+91 877 223 4411"
    },
    {
        id: 8,
        name: "Barista",
        city: "Tirupati",
        address: "Leela Mahal Circle, Tirupati",
        lat: 13.6317,
        lng: 79.4233,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "work"],
        openHours: { open: 9, close: 21 },
        rating: 4.2,
        phone: "+91 877 250 9922"
    },
    {
        id: 9,
        name: "Tea Trails",
        city: "Tirupati",
        address: "Near Alipiri Road, Tirupati",
        lat: 13.6289,
        lng: 79.4195,
        wifi: false,
        sockets: "low",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout", "quick"],
        openHours: { open: 10, close: 22 },
        rating: 4.1,
        phone: "+91 877 222 3344"
    },

    // ARUNACHAL PRADESH

    {
        id: 10,
        name: "Cafe 21",
        city: "Itanagar",
        address: "Ganga Market, Itanagar",
        lat: 27.0844,
        lng: 93.6053,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout", "reading"],
        openHours: { open: 9, close: 21 },
        rating: 4.2,
        phone: "+91 81318 12345"
    },
    {
        id: 11,
        name: "Brew House",
        city: "Itanagar",
        address: "Bank Tinali, Itanagar",
        lat: 27.0902,
        lng: 93.6121,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meeting", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.1,
        phone: "+91 81320 56789"
    },
    {
        id: 12,
        name: "Cafe Shillong Point",
        city: "Itanagar",
        address: "VIP Road, Itanagar",
        lat: 27.1003,
        lng: 93.6204,
        wifi: false,
        sockets: "low",
        seating: "basic",
        ac: false,
        bestFor: ["quick", "hangout"],
        openHours: { open: 8, close: 20 },
        rating: 4.0,
        phone: "+91 81310 99887"
    },

    {
        id: 13,
        name: "Cafe Aroma",
        city: "Naharlagun",
        address: "Model Village, Naharlagun",
        lat: 27.1047,
        lng: 93.6970,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "work"],
        openHours: { open: 9, close: 21 },
        rating: 4.2,
        phone: "+91 81322 33445"
    },
    {
        id: 14,
        name: "Tea Junction",
        city: "Naharlagun",
        address: "Nyokum Lapang Road, Naharlagun",
        lat: 27.1075,
        lng: 93.7023,
        wifi: false,
        sockets: "low",
        seating: "basic",
        ac: false,
        bestFor: ["quick", "hangout"],
        openHours: { open: 7, close: 22 },
        rating: 4.1,
        phone: "+91 81325 11223"
    },
    {
        id: 15,
        name: "Cafe Highland",
        city: "Naharlagun",
        address: "Sector C, Naharlagun",
        lat: 27.0982,
        lng: 93.6944,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "meeting"],
        openHours: { open: 10, close: 22 },
        rating: 4.0,
        phone: "+91 81321 77665"
    },

    {
        id: 16,
        name: "River View Cafe",
        city: "Pasighat",
        address: "Siang River Road, Pasighat",
        lat: 28.0656,
        lng: 95.3302,
        wifi: false,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout", "reading"],
        openHours: { open: 9, close: 20 },
        rating: 4.3,
        phone: "+91 81330 44556"
    },
    {
        id: 17,
        name: "Cafe Abor",
        city: "Pasighat",
        address: "Market Area, Pasighat",
        lat: 28.0668,
        lng: 95.3259,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "work"],
        openHours: { open: 10, close: 21 },
        rating: 4.1,
        phone: "+91 81331 88990"
    },
    {
        id: 18,
        name: "Tea Lounge",
        city: "Pasighat",
        address: "NH-52, Pasighat",
        lat: 28.0604,
        lng: 95.3280,
        wifi: false,
        sockets: "low",
        seating: "basic",
        ac: false,
        bestFor: ["quick"],
        openHours: { open: 8, close: 21 },
        rating: 4.0,
        phone: "+91 81332 22334"
    },

    // ASSAM

    {
        id: 19,
        name: "Cafe Hendrix",
        city: "Guwahati",
        address: "GS Road, Guwahati",
        lat: 26.1445,
        lng: 91.7362,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "study"],
        openHours: { open: 9, close: 22 },
        rating: 4.4,
        phone: "+91 361 233 4455"
    },
    {
        id: 20,
        name: "Kalita Spectrum",
        city: "Guwahati",
        address: "Zoo Road, Guwahati",
        lat: 26.1587,
        lng: 91.7903,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meeting", "hangout"],
        openHours: { open: 10, close: 23 },
        rating: 4.3,
        phone: "+91 361 246 7788"
    },
    {
        id: 21,
        name: "CCD",
        city: "Guwahati",
        address: "Paltan Bazaar, Guwahati",
        lat: 26.1805,
        lng: 91.7521,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["quick", "reading"],
        openHours: { open: 8, close: 23 },
        rating: 4.1,
        phone: "+91 361 251 3344"
    },

    {
        id: 22,
        name: "Cafe Junaki",
        city: "Dibrugarh",
        address: "Khalihamari, Dibrugarh",
        lat: 27.4836,
        lng: 94.9120,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "work"],
        openHours: { open: 9, close: 21 },
        rating: 4.2,
        phone: "+91 94350 11223"
    },
    {
        id: 23,
        name: "Tea Break Cafe",
        city: "Dibrugarh",
        address: "RKB Path, Dibrugarh",
        lat: 27.4729,
        lng: 94.9111,
        wifi: false,
        sockets: "low",
        seating: "basic",
        ac: false,
        bestFor: ["quick", "hangout"],
        openHours: { open: 8, close: 22 },
        rating: 4.1,
        phone: "+91 94351 44556"
    },
    {
        id: 24,
        name: "Cafe Coffee Day",
        city: "Dibrugarh",
        address: "AT Road, Dibrugarh",
        lat: 27.4761,
        lng: 94.9087,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "work"],
        openHours: { open: 8, close: 23 },
        rating: 4.0,
        phone: "+91 94352 77889"
    },

    {
        id: 25,
        name: "Cafe Red Carpet",
        city: "Jorhat",
        address: "Garali, Jorhat",
        lat: 26.7573,
        lng: 94.2037,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meeting", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.2,
        phone: "+91 99545 11223"
    },
    {
        id: 26,
        name: "Tea Galaxy",
        city: "Jorhat",
        address: "A.T. Road, Jorhat",
        lat: 26.7519,
        lng: 94.2164,
        wifi: false,
        sockets: "low",
        seating: "basic",
        ac: false,
        bestFor: ["quick"],
        openHours: { open: 8, close: 21 },
        rating: 4.0,
        phone: "+91 99546 33445"
    },
    {
        id: 27,
        name: "Cafe Coffee Day",
        city: "Jorhat",
        address: "Mariani Road, Jorhat",
        lat: 26.7604,
        lng: 94.2151,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "reading"],
        openHours: { open: 8, close: 23 },
        rating: 4.1,
        phone: "+91 99547 55667"
    },

    // CHATTISGARH
    {
        id: 37,
        name: "Cafe Junoon",
        city: "Raipur",
        address: "Civil Lines, Raipur, Chhattisgarh",
        lat: 21.2336,
        lng: 81.6330,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 11, close: 23 },
        rating: 4.4,
        phone: "+91 771 4032123"
    },
    {
        id: 38,
        name: "Cafe Coffee Day",
        city: "Raipur",
        address: "Pandri, Raipur, Chhattisgarh",
        lat: 21.2488,
        lng: 81.6321,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "work"],
        openHours: { open: 9, close: 23 },
        rating: 4.1,
        phone: "+91 771 4215566"
    },
    {
        id: 39,
        name: "Mocha",
        city: "Raipur",
        address: "Magneto Mall, Raipur, Chhattisgarh",
        lat: 21.2545,
        lng: 81.6189,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout", "meetings"],
        openHours: { open: 11, close: 23 },
        rating: 4.3,
        phone: "+91 771 4098899"
    },
    {
        id: 40,
        name: "Cafe Coffee Day",
        city: "Bilaspur",
        address: "Vyapar Vihar, Bilaspur, Chhattisgarh",
        lat: 22.0797,
        lng: 82.1391,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "work"],
        openHours: { open: 9, close: 22 },
        rating: 4.0,
        phone: "+91 7752 234567"
    },
    {
        id: 41,
        name: "Coffee Day Square",
        city: "Bilaspur",
        address: "Link Road, Bilaspur, Chhattisgarh",
        lat: 22.0874,
        lng: 82.1502,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 10, close: 23 },
        rating: 4.2,
        phone: "+91 7752 229900"
    },
    {
        id: 42,
        name: "Chai Sutta Bar",
        city: "Bilaspur",
        address: "Rajkishore Nagar, Bilaspur, Chhattisgarh",
        lat: 22.0908,
        lng: 82.1426,
        wifi: false,
        sockets: "low",
        seating: "casual",
        ac: false,
        bestFor: ["quick", "hangout"],
        openHours: { open: 8, close: 22 },
        rating: 4.1,
        phone: "+91 90099 11223"
    },
    {
        id: 43,
        name: "Cafe Coffee Day",
        city: "Bhilai",
        address: "Civic Centre, Bhilai, Chhattisgarh",
        lat: 21.2167,
        lng: 81.3265,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "work"],
        openHours: { open: 9, close: 23 },
        rating: 4.1,
        phone: "+91 788 4034455"
    },
    {
        id: 44,
        name: "Brewberrys Cafe",
        city: "Bhilai",
        address: "Supela, Bhilai, Chhattisgarh",
        lat: 21.2142,
        lng: 81.3541,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 10, close: 22 },
        rating: 4.3,
        phone: "+91 79995 66778"
    },
    {
        id: 45,
        name: "Chai Ho Jaye",
        city: "Bhilai",
        address: "Nehru Nagar, Bhilai, Chhattisgarh",
        lat: 21.2079,
        lng: 81.3362,
        wifi: false,
        sockets: "low",
        seating: "casual",
        ac: false,
        bestFor: ["quick", "hangout"],
        openHours: { open: 8, close: 21 },
        rating: 4.0,
        phone: "+91 81091 33445"
    },

    // GOA
    {
        id: 46,
        name: "Cafe Bodega",
        city: "Panaji",
        address: "Sunaparanta Centre for the Arts, Panaji, Goa",
        lat: 15.4909,
        lng: 73.8278,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "reading"],
        openHours: { open: 10, close: 20 },
        rating: 4.5,
        phone: "+91 832 2421312"
    },
    {
        id: 47,
        name: "Cafe Tato",
        city: "Panaji",
        address: "18th June Road, Panaji, Goa",
        lat: 15.4923,
        lng: 73.8271,
        wifi: false,
        sockets: "low",
        seating: "casual",
        ac: false,
        bestFor: ["quick", "hangout"],
        openHours: { open: 7, close: 19 },
        rating: 4.4,
        phone: "+91 832 2225295"
    },
    {
        id: 48,
        name: "Starbucks",
        city: "Panaji",
        address: "Mall de Goa, Panaji, Goa",
        lat: 15.5096,
        lng: 73.8293,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 10, close: 22 },
        rating: 4.3,
        phone: "+91 832 6710200"
    },
    {
        id: 49,
        name: "Cafe Tato Margao",
        city: "Margao",
        address: "Comba, Margao, Goa",
        lat: 15.2736,
        lng: 73.9581,
        wifi: false,
        sockets: "low",
        seating: "casual",
        ac: false,
        bestFor: ["quick", "hangout"],
        openHours: { open: 7, close: 20 },
        rating: 4.2,
        phone: "+91 832 2712156"
    },
    {
        id: 50,
        name: "Kareem's Cafe",
        city: "Margao",
        address: "Pajifond, Margao, Goa",
        lat: 15.2751,
        lng: 73.9643,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meetings", "hangout"],
        openHours: { open: 11, close: 23 },
        rating: 4.1,
        phone: "+91 832 2717788"
    },
    {
        id: 51,
        name: "Cafe Real",
        city: "Margao",
        address: "MG Road, Margao, Goa",
        lat: 15.2729,
        lng: 73.9589,
        wifi: false,
        sockets: "low",
        seating: "casual",
        ac: false,
        bestFor: ["quick"],
        openHours: { open: 8, close: 21 },
        rating: 4.3,
        phone: "+91 832 2704285"
    },
    {
        id: 52,
        name: "Cafe Coffee Day",
        city: "Vasco da Gama",
        address: "Airport Road, Vasco, Goa",
        lat: 15.3860,
        lng: 73.8440,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "work"],
        openHours: { open: 9, close: 22 },
        rating: 4.0,
        phone: "+91 832 2505566"
    },
    {
        id: 53,
        name: "D'Mello's Cafe",
        city: "Vasco da Gama",
        address: "Bogda Road, Vasco, Goa",
        lat: 15.3952,
        lng: 73.8156,
        wifi: false,
        sockets: "low",
        seating: "casual",
        ac: false,
        bestFor: ["quick", "hangout"],
        openHours: { open: 8, close: 20 },
        rating: 4.2,
        phone: "+91 832 2512345"
    },
    {
        id: 54,
        name: "Cafe Delicias",
        city: "Vasco da Gama",
        address: "Swatantra Path, Vasco, Goa",
        lat: 15.3868,
        lng: 73.8449,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meetings", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.1,
        phone: "+91 832 2509988"
    },

    // GUJARAT
    {
        id: 55,
        name: "Mocha",
        city: "Ahmedabad",
        address: "Bodakdev, Ahmedabad, Gujarat",
        lat: 23.0405,
        lng: 72.5076,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 11, close: 23 },
        rating: 4.4,
        phone: "+91 79 40321000"
    },
    {
        id: 56,
        name: "Java+",
        city: "Ahmedabad",
        address: "Prahlad Nagar, Ahmedabad, Gujarat",
        lat: 23.0121,
        lng: 72.5014,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "work"],
        openHours: { open: 9, close: 22 },
        rating: 4.3,
        phone: "+91 79 48901234"
    },
    {
        id: 57,
        name: "Cafe Coffee Day",
        city: "Ahmedabad",
        address: "CG Road, Ahmedabad, Gujarat",
        lat: 23.0258,
        lng: 72.5590,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study"],
        openHours: { open: 9, close: 23 },
        rating: 4.1,
        phone: "+91 79 26445566"
    },
    {
        id: 58,
        name: "Meraki The Coffee House",
        city: "Surat",
        address: "Vesu, Surat, Gujarat",
        lat: 21.1415,
        lng: 72.7704,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 10, close: 23 },
        rating: 4.5,
        phone: "+91 261 4103344"
    },
    {
        id: 59,
        name: "Unwind Cafe",
        city: "Surat",
        address: "City Light, Surat, Gujarat",
        lat: 21.1676,
        lng: 72.7902,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout", "meetings"],
        openHours: { open: 11, close: 23 },
        rating: 4.3,
        phone: "+91 261 2257788"
    },
    {
        id: 60,
        name: "Cafe Coffee Day",
        city: "Surat",
        address: "Adajan, Surat, Gujarat",
        lat: 21.2003,
        lng: 72.7913,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study"],
        openHours: { open: 9, close: 22 },
        rating: 4.0,
        phone: "+91 261 2785566"
    },
    {
        id: 61,
        name: "Modernist Coffee",
        city: "Vadodara",
        address: "Alkapuri, Vadodara, Gujarat",
        lat: 22.3072,
        lng: 73.1812,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "reading"],
        openHours: { open: 9, close: 22 },
        rating: 4.6,
        phone: "+91 265 2345678"
    },
    {
        id: 62,
        name: "Curators Coffee",
        city: "Vadodara",
        address: "Gotri Road, Vadodara, Gujarat",
        lat: 22.3178,
        lng: 73.1642,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meetings", "hangout"],
        openHours: { open: 10, close: 23 },
        rating: 4.4,
        phone: "+91 265 2987766"
    },
    {
        id: 63,
        name: "Cafe Coffee Day",
        city: "Vadodara",
        address: "Sayajigunj, Vadodara, Gujarat",
        lat: 22.3106,
        lng: 73.1843,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study"],
        openHours: { open: 9, close: 22 },
        rating: 4.1,
        phone: "+91 265 2223344"
    },

    //HARYANA
    {
        id: 64,
        name: "Blue Tokai Coffee Roasters",
        city: "Gurugram",
        address: "32nd Avenue, Gurugram, Haryana",
        lat: 28.4698,
        lng: 77.0638,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 8, close: 23 },
        rating: 4.6,
        phone: "+91 124 4983200"
    },
    {
        id: 65,
        name: "Di Ghent Cafe",
        city: "Gurugram",
        address: "Cross Point Mall, DLF Phase 4, Gurugram",
        lat: 28.4675,
        lng: 77.0790,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "hangout"],
        openHours: { open: 9, close: 22 },
        rating: 4.5,
        phone: "+91 124 4389090"
    },
    {
        id: 66,
        name: "Cafe Coffee Day",
        city: "Gurugram",
        address: "Cyber Hub, DLF Phase 3, Gurugram",
        lat: 28.4946,
        lng: 77.0881,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "quick"],
        openHours: { open: 9, close: 23 },
        rating: 4.1,
        phone: "+91 124 4567788"
    },
    {
        id: 67,
        name: "Cafe Parmesan",
        city: "Faridabad",
        address: "Sector 16, Faridabad, Haryana",
        lat: 28.4089,
        lng: 77.3187,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meetings", "hangout"],
        openHours: { open: 11, close: 23 },
        rating: 4.4,
        phone: "+91 129 4051122"
    },
    {
        id: 68,
        name: "Cafe Coffee Day",
        city: "Faridabad",
        address: "Crown Interiorz Mall, Faridabad",
        lat: 28.3927,
        lng: 77.3056,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study"],
        openHours: { open: 9, close: 22 },
        rating: 4.0,
        phone: "+91 129 4195566"
    },
    {
        id: 69,
        name: "The Coffee Bean & Tea Leaf",
        city: "Faridabad",
        address: "Sector 14, Faridabad, Haryana",
        lat: 28.3958,
        lng: 77.3132,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 8, close: 22 },
        rating: 4.3,
        phone: "+91 129 4102233"
    },
    {
        id: 70,
        name: "Cafe Coffee Day",
        city: "Panipat",
        address: "GT Road, Panipat, Haryana",
        lat: 29.3909,
        lng: 76.9635,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "quick"],
        openHours: { open: 9, close: 22 },
        rating: 4.0,
        phone: "+91 180 4023344"
    },
    {
        id: 71,
        name: "Barista",
        city: "Panipat",
        address: "Model Town, Panipat, Haryana",
        lat: 29.3896,
        lng: 76.9698,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.1,
        phone: "+91 180 4017788"
    },
    {
        id: 72,
        name: "Cafe Brewberrys",
        city: "Panipat",
        address: "Sector 25, Panipat, Haryana",
        lat: 29.4032,
        lng: 76.9874,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 9, close: 23 },
        rating: 4.2,
        phone: "+91 180 4105566"
    },

    //HIMACHAL PRADESH
    {
        id: 73,
        name: "Cafe Simla Times",
        city: "Shimla",
        address: "Mall Road, Shimla, Himachal Pradesh",
        lat: 31.1048,
        lng: 77.1734,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: false,
        bestFor: ["reading", "hangout"],
        openHours: { open: 9, close: 21 },
        rating: 4.5,
        phone: "+91 177 2657777"
    },
    {
        id: 74,
        name: "Wake & Bake Cafe",
        city: "Shimla",
        address: "Lower Bazaar, Shimla",
        lat: 31.1031,
        lng: 77.1722,
        wifi: true,
        sockets: "low",
        seating: "casual",
        ac: false,
        bestFor: ["hangout", "quick"],
        openHours: { open: 10, close: 22 },
        rating: 4.6,
        phone: "+91 177 2808899"
    },
    {
        id: 75,
        name: "Cafe Coffee Day",
        city: "Shimla",
        address: "Mall Road, Shimla",
        lat: 31.1041,
        lng: 77.1730,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: false,
        bestFor: ["study"],
        openHours: { open: 9, close: 21 },
        rating: 4.0,
        phone: "+91 177 2654455"
    },
    {
        id: 76,
        name: "Cafe 1947",
        city: "Manali",
        address: "Old Manali Road, Manali, Himachal Pradesh",
        lat: 32.2432,
        lng: 77.1892,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: false,
        bestFor: ["reading", "hangout"],
        openHours: { open: 9, close: 22 },
        rating: 4.7,
        phone: "+91 190 2255678"
    },
    {
        id: 77,
        name: "Drifter's Cafe",
        city: "Manali",
        address: "Old Manali, Himachal Pradesh",
        lat: 32.2441,
        lng: 77.1904,
        wifi: true,
        sockets: "low",
        seating: "casual",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 10, close: 23 },
        rating: 4.6,
        phone: "+91 190 2258899"
    },
    {
        id: 78,
        name: "Cafe Coffee Day",
        city: "Manali",
        address: "Mall Road, Manali",
        lat: 32.2396,
        lng: 77.1887,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: false,
        bestFor: ["study", "quick"],
        openHours: { open: 9, close: 21 },
        rating: 4.0,
        phone: "+91 190 2523344"
    },
    {
        id: 79,
        name: "Moonpeak Espresso",
        city: "Dharamshala",
        address: "Jogiwara Road, McLeod Ganj, Dharamshala",
        lat: 32.2426,
        lng: 76.3219,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: false,
        bestFor: ["work", "reading"],
        openHours: { open: 9, close: 21 },
        rating: 4.7,
        phone: "+91 189 2223344"
    },
    {
        id: 80,
        name: "Crepe Pancake Hut",
        city: "Dharamshala",
        address: "Bhagsu Road, McLeod Ganj",
        lat: 32.2439,
        lng: 76.3247,
        wifi: true,
        sockets: "low",
        seating: "casual",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 9, close: 22 },
        rating: 4.6,
        phone: "+91 189 2225566"
    },
    {
        id: 81,
        name: "Cafe Coffee Day",
        city: "Dharamshala",
        address: "Kotwali Bazaar, Dharamshala",
        lat: 32.2190,
        lng: 76.3234,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: false,
        bestFor: ["study"],
        openHours: { open: 9, close: 21 },
        rating: 4.0,
        phone: "+91 189 2267788"
    },

    // JHARKAND
    {
        id: 82,
        name: "Cafe Coffee Day",
        city: "Ranchi",
        address: "Main Road, Ranchi, Jharkhand",
        lat: 23.3700,
        lng: 85.3250,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "work"],
        openHours: { open: 9, close: 22 },
        rating: 4.1,
        phone: "+91 651 2334455"
    },
    {
        id: 83,
        name: "Barista",
        city: "Ranchi",
        address: "Lalpur Chowk, Ranchi, Jharkhand",
        lat: 23.3824,
        lng: 85.3318,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.2,
        phone: "+91 651 2547788"
    },
    {
        id: 84,
        name: "The Uptown Cafe",
        city: "Ranchi",
        address: "Morabadi, Ranchi, Jharkhand",
        lat: 23.3948,
        lng: 85.3216,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 11, close: 23 },
        rating: 4.3,
        phone: "+91 651 2601122"
    },
    {
        id: 85,
        name: "Cafe Regal",
        city: "Jamshedpur",
        address: "Bistupur, Jamshedpur, Jharkhand",
        lat: 22.7946,
        lng: 86.1846,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meetings", "hangout"],
        openHours: { open: 11, close: 23 },
        rating: 4.4,
        phone: "+91 657 2223344"
    },
    {
        id: 86,
        name: "Cafe Coffee Day",
        city: "Jamshedpur",
        address: "Sakchi Market, Jamshedpur",
        lat: 22.8046,
        lng: 86.2029,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study"],
        openHours: { open: 9, close: 22 },
        rating: 4.0,
        phone: "+91 657 2445566"
    },
    {
        id: 87,
        name: "The Chocolate Room",
        city: "Jamshedpur",
        address: "Bistupur, Jamshedpur",
        lat: 22.7962,
        lng: 86.1859,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.2,
        phone: "+91 657 2317788"
    },
    {
        id: 88,
        name: "Cafe Coffee Day",
        city: "Dhanbad",
        address: "Hirapur, Dhanbad, Jharkhand",
        lat: 23.7957,
        lng: 86.4304,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study", "quick"],
        openHours: { open: 9, close: 22 },
        rating: 4.0,
        phone: "+91 326 2304455"
    },
    {
        id: 89,
        name: "Cafe 18",
        city: "Dhanbad",
        address: "Saraidhela, Dhanbad",
        lat: 23.8121,
        lng: 86.4629,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout", "meetings"],
        openHours: { open: 11, close: 23 },
        rating: 4.1,
        phone: "+91 326 2218899"
    },
    {
        id: 90,
        name: "Cafe Buddy's Espresso",
        city: "Dhanbad",
        address: "Bank More, Dhanbad",
        lat: 23.7996,
        lng: 86.4317,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "study"],
        openHours: { open: 10, close: 22 },
        rating: 4.2,
        phone: "+91 326 2236677"
    }
    ,

    // KARNATAKA
    {
        id: 91,
        name: "Blue Tokai Coffee Roasters",
        city: "Bengaluru",
        address: "Indiranagar, Bengaluru, Karnataka",
        lat: 12.9719,
        lng: 77.6412,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 8, close: 23 },
        rating: 4.6,
        phone: "+91 80 41125678"
    },
    {
        id: 92,
        name: "Third Wave Coffee",
        city: "Bengaluru",
        address: "Koramangala 5th Block, Bengaluru",
        lat: 12.9352,
        lng: 77.6193,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "study"],
        openHours: { open: 8, close: 23 },
        rating: 4.5,
        phone: "+91 80 41478293"
    },
    {
        id: 93,
        name: "Matteo Coffea",
        city: "Bengaluru",
        address: "Church Street, Bengaluru",
        lat: 12.9756,
        lng: 77.6046,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "hangout"],
        openHours: { open: 9, close: 22 },
        rating: 4.4,
        phone: "+91 80 25591234"
    },
    {
        id: 94,
        name: "Depth N Green",
        city: "Mysuru",
        address: "Kalidasa Road, Mysuru, Karnataka",
        lat: 12.3080,
        lng: 76.6409,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "reading"],
        openHours: { open: 10, close: 22 },
        rating: 4.5,
        phone: "+91 821 4001122"
    },
    {
        id: 95,
        name: "Cafe Coffee Day",
        city: "Mysuru",
        address: "Mall of Mysore, Mysuru",
        lat: 12.2967,
        lng: 76.6394,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study"],
        openHours: { open: 9, close: 22 },
        rating: 4.0,
        phone: "+91 821 2445566"
    },
    {
        id: 96,
        name: "The Old House Cafe",
        city: "Mysuru",
        address: "Vivekananda Road, Mysuru",
        lat: 12.3116,
        lng: 76.6482,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 22 },
        rating: 4.3,
        phone: "+91 821 4267788"
    },
    {
        id: 97,
        name: "Diesel Cafe",
        city: "Mangaluru",
        address: "Bejai, Mangaluru, Karnataka",
        lat: 12.8926,
        lng: 74.8560,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meetings", "hangout"],
        openHours: { open: 10, close: 23 },
        rating: 4.4,
        phone: "+91 824 4255566"
    },
    {
        id: 98,
        name: "Brick House",
        city: "Mangaluru",
        address: "Balmatta, Mangaluru",
        lat: 12.8847,
        lng: 74.8405,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "study"],
        openHours: { open: 9, close: 22 },
        rating: 4.5,
        phone: "+91 824 2456677"
    },
    {
        id: 99,
        name: "Cafe Coffee Day",
        city: "Mangaluru",
        address: "Forum Fiza Mall, Mangaluru",
        lat: 12.8806,
        lng: 74.8432,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["quick", "study"],
        openHours: { open: 9, close: 22 },
        rating: 4.0,
        phone: "+91 824 2434455"
    },

    // MADHYA PRADESH
    {
        id: 100,
        name: "Handcrafted Cafe",
        city: "Bhopal",
        address: "DB City Mall, Bhopal, Madhya Pradesh",
        lat: 23.2324,
        lng: 77.4341,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 10, close: 23 },
        rating: 4.4,
        phone: "+91 755 6644555"
    },
    {
        id: 101,
        name: "Cafe Coffee Day",
        city: "Bhopal",
        address: "MP Nagar Zone II, Bhopal",
        lat: 23.2337,
        lng: 77.4345,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study"],
        openHours: { open: 9, close: 22 },
        rating: 4.1,
        phone: "+91 755 2556677"
    },
    {
        id: 102,
        name: "Bake N Shake",
        city: "Bhopal",
        address: "Arera Colony, Bhopal",
        lat: 23.2167,
        lng: 77.4331,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 23 },
        rating: 4.3,
        phone: "+91 755 4223344"
    },
    {
        id: 103,
        name: "Mr. Beans",
        city: "Indore",
        address: "Vijay Nagar, Indore, Madhya Pradesh",
        lat: 22.7533,
        lng: 75.8937,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "study"],
        openHours: { open: 9, close: 23 },
        rating: 4.5,
        phone: "+91 731 4045566"
    },
    {
        id: 104,
        name: "Chapter One",
        city: "Indore",
        address: "Saket Nagar, Indore",
        lat: 22.7244,
        lng: 75.8839,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "work"],
        openHours: { open: 10, close: 22 },
        rating: 4.6,
        phone: "+91 731 4967788"
    },
    {
        id: 105,
        name: "Cafe Terraza",
        city: "Indore",
        address: "C21 Mall, Indore",
        lat: 22.7510,
        lng: 75.8956,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meetings"],
        openHours: { open: 10, close: 23 },
        rating: 4.2,
        phone: "+91 731 4012345"
    },
    {
        id: 106,
        name: "Mocha",
        city: "Gwalior",
        address: "City Centre, Gwalior",
        lat: 26.2183,
        lng: 78.1828,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meetings"],
        openHours: { open: 11, close: 23 },
        rating: 4.3,
        phone: "+91 751 4012233"
    },
    {
        id: 107,
        name: "Cafe Coffee Day",
        city: "Gwalior",
        address: "DB Mall, Gwalior",
        lat: 26.2144,
        lng: 78.1747,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study"],
        openHours: { open: 9, close: 22 },
        rating: 4.0,
        phone: "+91 751 2456677"
    },
    {
        id: 108,
        name: "Captain's Cafe",
        city: "Gwalior",
        address: "Thatipur, Gwalior",
        lat: 26.2331,
        lng: 78.2121,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 12, close: 22 },
        rating: 4.2,
        phone: "+91 751 4099988"
    },


    // MAHARASHTRA
    {
        id: 109,
        name: "Subko Coffee Roasters",
        city: "Mumbai",
        address: "Bandra West, Mumbai, Maharashtra",
        lat: 19.0596,
        lng: 72.8295,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meetings"],
        openHours: { open: 9, close: 23 },
        rating: 4.6,
        phone: "+91 22 26401234"
    },
    {
        id: 110,
        name: "Blue Tokai Coffee Roasters",
        city: "Mumbai",
        address: "Colaba, Mumbai",
        lat: 18.9217,
        lng: 72.8331,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "study"],
        openHours: { open: 8, close: 23 },
        rating: 4.5,
        phone: "+91 22 22024455"
    },
    {
        id: 111,
        name: "Leaping Windows",
        city: "Mumbai",
        address: "Versova, Andheri West, Mumbai",
        lat: 19.1304,
        lng: 72.8162,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "work"],
        openHours: { open: 10, close: 22 },
        rating: 4.4,
        phone: "+91 22 26345566"
    },
    {
        id: 112,
        name: "Pagdandi Books Chai Cafe",
        city: "Pune",
        address: "Baner, Pune, Maharashtra",
        lat: 18.5590,
        lng: 73.7890,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "study"],
        openHours: { open: 10, close: 22 },
        rating: 4.6,
        phone: "+91 20 65234567"
    },
    {
        id: 113,
        name: "Cafe Peter",
        city: "Pune",
        address: "FC Road, Pune",
        lat: 18.5204,
        lng: 73.8567,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meetings"],
        openHours: { open: 9, close: 23 },
        rating: 4.3,
        phone: "+91 20 25544556"
    },
    {
        id: 114,
        name: "Third Wave Coffee",
        city: "Pune",
        address: "Koregaon Park, Pune",
        lat: 18.5362,
        lng: 73.8939,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work"],
        openHours: { open: 8, close: 23 },
        rating: 4.5,
        phone: "+91 20 41237890"
    },
    {
        id: 115,
        name: "Corridor Seven Coffee Roasters",
        city: "Nagpur",
        address: "Civil Lines, Nagpur, Maharashtra",
        lat: 21.1498,
        lng: 79.0806,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "study"],
        openHours: { open: 9, close: 23 },
        rating: 4.7,
        phone: "+91 712 2567788"
    },
    {
        id: 116,
        name: "Three Beans Cafe",
        city: "Nagpur",
        address: "Dharampeth, Nagpur",
        lat: 21.1355,
        lng: 79.0633,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["meetings"],
        openHours: { open: 10, close: 22 },
        rating: 4.4,
        phone: "+91 712 4045566"
    },
    {
        id: 117,
        name: "Cafe Coffee Day",
        city: "Nagpur",
        address: "Trillium Mall, Nagpur",
        lat: 21.1458,
        lng: 79.0882,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["study"],
        openHours: { open: 9, close: 22 },
        rating: 4.0,
        phone: "+91 712 2443344"
    },

    // MANIPUR
    {
        id: 118,
        name: "Classic Cafe",
        city: "Imphal East",
        address: "Porompat, Imphal East, Manipur",
        lat: 24.8092,
        lng: 93.9553,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 10, close: 21 },
        rating: 4.2,
        phone: "+91 385 2456677"
    },
    {
        id: 119,
        name: "Cafe Shillong",
        city: "Imphal East",
        address: "Porompat Road, Imphal",
        lat: 24.8124,
        lng: 93.9601,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["casual"],
        openHours: { open: 11, close: 21 },
        rating: 4.1,
        phone: "+91 385 2445566"
    },
    {
        id: 120,
        name: "Orange Cafe",
        city: "Imphal East",
        address: "Keishampat, Imphal",
        lat: 24.8045,
        lng: 93.9492,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 22 },
        rating: 4.0,
        phone: "+91 385 2458899"
    },


    // MEGHALAYA
    {
        id: 121,
        name: "Cafe Shillong Heritage",
        city: "Shillong",
        address: "Police Bazar, Shillong, Meghalaya",
        lat: 25.5769,
        lng: 91.8829,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout", "reading"],
        openHours: { open: 10, close: 21 },
        rating: 4.4,
        phone: "+91 364 2223344"
    },
    {
        id: 122,
        name: "Dylan's Cafe",
        city: "Shillong",
        address: "Laitumkhrah, Shillong",
        lat: 25.5736,
        lng: 91.8967,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 21 },
        rating: 4.3,
        phone: "+91 364 2501234"
    },
    {
        id: 123,
        name: "ML 05 Cafe",
        city: "Shillong",
        address: "Laitumkhrah Main Road, Shillong",
        lat: 25.5748,
        lng: 91.8979,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: false,
        bestFor: ["study", "casual work"],
        openHours: { open: 9, close: 22 },
        rating: 4.5,
        phone: "+91 364 2556677"
    },
    {
        id: 124,
        name: "Red Hill Cafe",
        city: "Tura",
        address: "Lower Chandmari, Tura, Meghalaya",
        lat: 25.5147,
        lng: 90.2039,
        wifi: false,
        sockets: "none",
        seating: "basic",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 20 },
        rating: 3.9,
        phone: "N/A"
    },
    {
        id: 125,
        name: "Cafe 7",
        city: "Tura",
        address: "Araimile, Tura",
        lat: 25.5122,
        lng: 90.2101,
        wifi: false,
        sockets: "none",
        seating: "basic",
        ac: false,
        bestFor: ["casual"],
        openHours: { open: 12, close: 20 },
        rating: 3.8,
        phone: "N/A"
    },
    {
        id: 126,
        name: "Phrang Roy Cafe",
        city: "Jowai",
        address: "Ialong, Jowai, Meghalaya",
        lat: 25.4473,
        lng: 92.2056,
        wifi: false,
        sockets: "none",
        seating: "basic",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 20 },
        rating: 3.9,
        phone: "N/A"
    },


    // MIZORAM
    {
        id: 127,
        name: "Cafe de Sangkima",
        city: "Aizawl",
        address: "Dawrpui, Aizawl, Mizoram",
        lat: 23.7271,
        lng: 92.7176,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 10, close: 21 },
        rating: 4.2,
        phone: "+91 389 2324455"
    },
    {
        id: 128,
        name: "Cafe Fika",
        city: "Aizawl",
        address: "Chanmari, Aizawl",
        lat: 23.7366,
        lng: 92.7264,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: false,
        bestFor: ["study", "reading"],
        openHours: { open: 9, close: 21 },
        rating: 4.4,
        phone: "+91 389 2335566"
    },
    {
        id: 129,
        name: "Zo Cafe",
        city: "Aizawl",
        address: "Zarkawt, Aizawl",
        lat: 23.7319,
        lng: 92.7209,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["casual"],
        openHours: { open: 10, close: 21 },
        rating: 4.1,
        phone: "+91 389 2347788"
    },
    {
        id: 130,
        name: "Lunglei Cafe",
        city: "Lunglei",
        address: "Venglai, Lunglei, Mizoram",
        lat: 22.8925,
        lng: 92.7422,
        wifi: false,
        sockets: "none",
        seating: "basic",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 20 },
        rating: 3.8,
        phone: "N/A"
    },
    {
        id: 131,
        name: "Border View Cafe",
        city: "Champhai",
        address: "Vengsang, Champhai, Mizoram",
        lat: 23.4585,
        lng: 93.3256,
        wifi: false,
        sockets: "none",
        seating: "basic",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 20 },
        rating: 3.9,
        phone: "N/A"
    },


    //NAGALAND
    {
        id: 132,
        name: "Cafe D",
        city: "Kohima",
        address: "PR Hill, Kohima, Nagaland",
        lat: 25.6747,
        lng: 94.1100,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["reading", "hangout"],
        openHours: { open: 10, close: 20 },
        rating: 4.3,
        phone: "+91 370 2290456"
    },
    {
        id: 133,
        name: "The Garden Cafe",
        city: "Kohima",
        address: "Midland Colony, Kohima",
        lat: 25.6759,
        lng: 94.1084,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 20 },
        rating: 4.1,
        phone: "N/A"
    },
    {
        id: 134,
        name: "The Heritage Cafe",
        city: "Kohima",
        address: "Kezoma Village Road, Kohima",
        lat: 25.6678,
        lng: 94.1051,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["casual"],
        openHours: { open: 10, close: 19 },
        rating: 4.0,
        phone: "N/A"
    },
    {
        id: 135,
        name: "Cafe culture",
        city: "Dimapur",
        address: "Super Market Area, Dimapur, Nagaland",
        lat: 25.9091,
        lng: 93.7276,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meeting"],
        openHours: { open: 9, close: 21 },
        rating: 4.2,
        phone: "+91 3862 224455"
    },
    {
        id: 136,
        name: "The Coffee Cup",
        city: "Dimapur",
        address: "Walford Colony, Dimapur",
        lat: 25.9133,
        lng: 93.7214,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "hangout"],
        openHours: { open: 10, close: 21 },
        rating: 4.1,
        phone: "+91 3862 226677"
    },
    {
        id: 137,
        name: "Hide Out Cafe",
        city: "Dimapur",
        address: "Duncan Basti, Dimapur",
        lat: 25.9068,
        lng: 93.7312,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 20 },
        rating: 4.0,
        phone: "N/A"
    },
    {
        id: 138,
        name: "Cafe Eden",
        city: "Mokokchung",
        address: "Along Road, Mokokchung, Nagaland",
        lat: 26.3245,
        lng: 94.5139,
        wifi: false,
        sockets: "none",
        seating: "basic",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 20 },
        rating: 3.9,
        phone: "N/A"
    },
    {
        id: 139,
        name: "Hill View Cafe",
        city: "Mokokchung",
        address: "IM Road, Mokokchung",
        lat: 26.3258,
        lng: 94.5116,
        wifi: false,
        sockets: "none",
        seating: "basic",
        ac: false,
        bestFor: ["casual"],
        openHours: { open: 10, close: 19 },
        rating: 3.8,
        phone: "N/A"
    },


    // ODISHA
    {
        id: 140,
        name: "Bocca Cafe",
        city: "Bhubaneswar",
        address: "DLF Cyber City, Bhubaneswar, Odisha",
        lat: 20.3555,
        lng: 85.8180,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meeting"],
        openHours: { open: 9, close: 22 },
        rating: 4.5,
        phone: "+91 674 3500123"
    },
    {
        id: 141,
        name: "Cafe Coffee Day",
        city: "Bhubaneswar",
        address: "Esplanade One Mall, Bhubaneswar",
        lat: 20.2961,
        lng: 85.8245,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.1,
        phone: "+91 674 2578899"
    },
    {
        id: 142,
        name: "Brown n Cream",
        city: "Bhubaneswar",
        address: "Nayapalli, Bhubaneswar, Odisha",
        lat: 20.3006,
        lng: 85.8189,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.2,
        phone: "+91 674 2387654"
    },
    {
        id: 143,
        name: "Cafe Coffee Day",
        city: "Cuttack",
        address: "Badambadi, Cuttack, Odisha",
        lat: 20.4635,
        lng: 85.8797,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meeting"],
        openHours: { open: 10, close: 21 },
        rating: 4.0,
        phone: "+91 671 2314455"
    },
    {
        id: 144,
        name: "Moody Blues Cafe",
        city: "Cuttack",
        address: "College Square, Cuttack",
        lat: 20.4691,
        lng: 85.8791,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 20 },
        rating: 4.1,
        phone: "N/A"
    },
    {
        id: 145,
        name: "Coffee Culture",
        city: "Cuttack",
        address: "Link Road, Cuttack, Odisha",
        lat: 20.4608,
        lng: 85.8819,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "hangout"],
        openHours: { open: 10, close: 21 },
        rating: 4.0,
        phone: "N/A"
    },
    {
        id: 146,
        name: "Cafe Coffee Day",
        city: "Rourkela",
        address: "Forum Galleria Mall, Rourkela, Odisha",
        lat: 22.2604,
        lng: 84.8536,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.1,
        phone: "+91 661 2503344"
    },
    {
        id: 147,
        name: "The Chocolate Room",
        city: "Rourkela",
        address: "Civil Township, Rourkela",
        lat: 22.2589,
        lng: 84.8472,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 22 },
        rating: 4.2,
        phone: "N/A"
    },
    {
        id: 148,
        name: "Cafe De Paris",
        city: "Rourkela",
        address: "Udit Nagar, Rourkela, Odisha",
        lat: 22.2516,
        lng: 84.8488,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["casual"],
        openHours: { open: 11, close: 20 },
        rating: 4.0,
        phone: "N/A"
    },

    // PUNJAB
    {
        id: 149,
        name: "Cafe Coffee Day",
        city: "Amritsar",
        address: "Mall of Amritsar, Amritsar, Punjab",
        lat: 31.6340,
        lng: 74.8723,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.1,
        phone: "+91 183 5001234"
    },
    {
        id: 150,
        name: "Starbucks",
        city: "Amritsar",
        address: "Ranjit Avenue, Amritsar, Punjab",
        lat: 31.6576,
        lng: 74.8726,
        wifi: true,
        sockets: "high",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "meeting"],
        openHours: { open: 8, close: 23 },
        rating: 4.4,
        phone: "+91 183 5206789"
    },
    {
        id: 151,
        name: "Cafe Oz",
        city: "Amritsar",
        address: "Green Avenue, Amritsar",
        lat: 31.6484,
        lng: 74.8720,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 22 },
        rating: 4.2,
        phone: "N/A"
    },
    {
        id: 152,
        name: "Cafe Coffee Day",
        city: "Ludhiana",
        address: "MBD Neopolis Mall, Ludhiana, Punjab",
        lat: 30.9010,
        lng: 75.8573,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.0,
        phone: "+91 161 5034455"
    },
    {
        id: 153,
        name: "Bistro 226",
        city: "Ludhiana",
        address: "Sarabha Nagar, Ludhiana",
        lat: 30.8957,
        lng: 75.8476,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: true,
        bestFor: ["meeting", "hangout"],
        openHours: { open: 11, close: 23 },
        rating: 4.3,
        phone: "+91 161 4678899"
    },
    {
        id: 154,
        name: "The Chocolate Room",
        city: "Ludhiana",
        address: "Ferozepur Road, Ludhiana",
        lat: 30.8812,
        lng: 75.8549,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 22 },
        rating: 4.2,
        phone: "N/A"
    },
    {
        id: 155,
        name: "Cafe Coffee Day",
        city: "Jalandhar",
        address: "Model Town, Jalandhar, Punjab",
        lat: 31.3260,
        lng: 75.5762,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.0,
        phone: "+91 181 5023344"
    },
    {
        id: 156,
        name: "Barista",
        city: "Jalandhar",
        address: "GTB Nagar, Jalandhar",
        lat: 31.3256,
        lng: 75.5798,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: true,
        bestFor: ["reading", "hangout"],
        openHours: { open: 9, close: 21 },
        rating: 4.1,
        phone: "+91 181 4698877"
    },
    {
        id: 157,
        name: "Cafe BrewBakes",
        city: "Jalandhar",
        address: "Urban Estate Phase 1, Jalandhar",
        lat: 31.3139,
        lng: 75.5682,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["casual"],
        openHours: { open: 11, close: 20 },
        rating: 4.0,
        phone: "N/A"
    },


    // RAJASTHAN
    {
        id: 158,
        name: "Tapri Central",
        city: "Jaipur",
        address: "Bani Park, Jaipur, Rajasthan",
        lat: 26.9379,
        lng: 75.8048,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "reading"],
        openHours: { open: 8, close: 22 },
        rating: 4.6,
        phone: "+91 141 2206555"
    },
    {
        id: 159,
        name: "Cafe Coffee Day",
        city: "Jaipur",
        address: "MI Road, Jaipur, Rajasthan",
        lat: 26.9157,
        lng: 75.8183,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.1,
        phone: "+91 141 2378899"
    },
    {
        id: 160,
        name: "The Tattoo Cafe & Lounge",
        city: "Jaipur",
        address: "Amer Road, Jaipur",
        lat: 26.9886,
        lng: 75.8510,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: true,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 23 },
        rating: 4.3,
        phone: "N/A"
    },
    {
        id: 161,
        name: "Cafe Sheesh Mahal",
        city: "Jodhpur",
        address: "Stepwell Road, Jodhpur, Rajasthan",
        lat: 26.2972,
        lng: 73.0184,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["casual", "hangout"],
        openHours: { open: 9, close: 21 },
        rating: 4.5,
        phone: "N/A"
    },
    {
        id: 162,
        name: "Cafe Coffee Day",
        city: "Jodhpur",
        address: "Paota Circle, Jodhpur",
        lat: 26.2926,
        lng: 73.0365,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.0,
        phone: "+91 291 2435566"
    },
    {
        id: 163,
        name: "Cafe Laalten",
        city: "Jodhpur",
        address: "Circuit House Road, Jodhpur",
        lat: 26.2666,
        lng: 73.0057,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 11, close: 22 },
        rating: 4.2,
        phone: "N/A"
    },
    {
        id: 164,
        name: "Jheel's Ginger Coffee Bar & Bakery",
        city: "Udaipur",
        address: "Hanuman Ghat, Udaipur, Rajasthan",
        lat: 24.5764,
        lng: 73.6831,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["reading", "casual"],
        openHours: { open: 8, close: 20 },
        rating: 4.6,
        phone: "N/A"
    },
    {
        id: 165,
        name: "Cafe Coffee Day",
        city: "Udaipur",
        address: "Celebration Mall, Udaipur",
        lat: 24.5865,
        lng: 73.7125,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.1,
        phone: "+91 294 3058899"
    },
    {
        id: 166,
        name: "Cafe Edelweiss",
        city: "Udaipur",
        address: "Gangaur Ghat, Udaipur",
        lat: 24.5769,
        lng: 73.6839,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 9, close: 21 },
        rating: 4.4,
        phone: "N/A"
    },


    // SIKKIM
    {
        id: 167,
        name: "Cafe Live & Loud",
        city: "Gangtok",
        address: "M.G. Marg, Gangtok, Sikkim",
        lat: 27.3314,
        lng: 88.6138,
        wifi: true,
        sockets: "low",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout", "reading"],
        openHours: { open: 9, close: 21 },
        rating: 4.4,
        phone: "N/A"
    },
    {
        id: 168,
        name: "Taste of Tibet",
        city: "Gangtok",
        address: "M.G. Marg, Gangtok",
        lat: 27.3319,
        lng: 88.6146,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["casual"],
        openHours: { open: 10, close: 20 },
        rating: 4.5,
        phone: "N/A"
    },
    {
        id: 169,
        name: "Cafe Coffee Day",
        city: "Gangtok",
        address: "Deorali, Gangtok, Sikkim",
        lat: 27.3208,
        lng: 88.6111,
        wifi: true,
        sockets: "medium",
        seating: "comfortable",
        ac: true,
        bestFor: ["work", "hangout"],
        openHours: { open: 10, close: 22 },
        rating: 4.1,
        phone: "+91 3592 250889"
    },
    {
        id: 170,
        name: "Cafe Central",
        city: "Namchi",
        address: "Central Park Area, Namchi, Sikkim",
        lat: 27.1656,
        lng: 88.3639,
        wifi: false,
        sockets: "none",
        seating: "comfortable",
        ac: false,
        bestFor: ["hangout"],
        openHours: { open: 10, close: 20 },
        rating: 4.1,
        phone: "N/A"
    },
    {
        id: 171,
        name: "Bakers Cafe",
        city: "Namchi",
        address: "Near Sai Mandir, Namchi",
        lat: 27.1642,
        lng: 88.3648,
        wifi: false,
        sockets: "none",
        seating: "basic",
        ac: false,
        bestFor: ["casual"],
        openHours: { open: 9, close: 19 },
        rating: 4.0,
        phone: "N/A"
    },
    {
        id: 172,
        name: "Himalayan Cafe",
        city: "Gyalshing",
        address: "Main Market, Gyalshing, Sikkim",  
        lat: 27.2894,
        lng: 88.2575,
        wifi: false,
        sockets: "none",
        seating: "basic",
        ac: false,
        bestFor: ["casual"],
        openHours: { open: 10, close: 19 },
        rating: 3.9,
        phone: "N/A"
    }

];
